version: '3'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: redis://redis:6379
    command: yarn dev
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  node_modules:
