version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    command: yarn server
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
