name: On push

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker-compose -f docker-compose.test.yml up -d --build
    - run: sleep 10

    - run: yarn playwright install --with-deps
    - run: yarn playwright test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - run: docker-compose -f docker-compose.test.yml exec -T web curl -f -LI http://localhost:3000/healthcheck

    - run: docker-compose -f docker-compose.test.yml down

  deploy_production:
    needs: test
    if: ${{ github.ref == 'refs/heads/v2' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: zenato/docker-action@master
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        repository: ${{ secrets.REGISTRY_REPO }}
        registry: ${{ secrets.REGISTRY_URL }}
        tag: beta
